### ISSUE TITLE
Error in system2(winutils, c("ls", shQuote(hivePath)), stdout = TRUE) : 

### ISSUE THREAD

**Issue by shahriariit** [steveloughran/winutils#10]
`> library(sparklyr)`
Warning message:
package ‘sparklyr’ was built under R version 3.4.4 
`> sc <- spark_connect(master = "local")`
* Using Spark: 2.2.0
Error in system2(winutils, c("ls", shQuote(hivePath)), stdout = TRUE) : 
  '"C:\Users\CSE - GB\AppData\Local\spark\spark-2.2.0-bin-hadoop2.7\tmp\hadoop\bin\winutils.exe"' not found
In addition: Warning message:
running command '"C:\Users\CSE - GB\AppData\Local\spark\spark-2.2.0-bin-hadoop2.7\tmp\hadoop\bin\winutils.exe" chmod 777 "C:\Users\CSE - GB\AppData\Local\spark\spark-2.2.0-bin-hadoop2.7\tmp\hive"' had status 127

**Comment by steveloughran** [comment]
Could be use of spaces in the executable; that breaks so many things. Can you stick up the full stack?
Note (issues with this stuff really belongs in the ASF JIRAs; this is just a build of the binaries off hadopo. But I'm curious now).

**Comment by TianWo** [comment]
I tried your 2.8.3 version. It works perfectly! Thank you so so much!! @steveloughran

**Comment by steveloughran** [comment]
happy :)

**Comment by celineperea** [comment]
> spark_conn <- spark_connect(master = "local")

- using sparklyr 

Error in prepare_windows_environment(spark_home, environment) : 
  FindFileOwnerAndPermission error (1789): La relation d?approbation entre cette station de travail et le domaine principal a échoué.
In addition: Warning message:
In system2(winutils, c("ls", shQuote(hivePath)), stdout = TRUE) :
  running command '"C:\spark-2.3.2-bin-hadoop2.7\tmp\hadoop\bin\winutils.exe" ls "C:\spark-2.3.2-bin-hadoop2.7\tmp\hive"' had status 1

**Comment by steveloughran** [comment]
sorry, I don't field support requests to related to commands executed.
