### ISSUE TITLE
Do you hava the file about bin of version  2.9?

### ISSUE THREAD

**Issue by chenjiaming2qiqi** [steveloughran/winutils#12]

**Comment by steveloughran** [comment]
actually no, not yet. I should sit down and do it.

**Comment by cdarlint** [comment]
@chenjiaming2qiqi take a look at https://github.com/cdarlint/winutils

**Comment by alibbbian** [comment]
version 2.10.1?

**Comment by steveloughran** [comment]
I'm not doing anything on this. And everyone should upgrade to hadoop 3.x anyway
