### ISSUE TITLE
Hadoop 3.1.1

### ISSUE THREAD

**Issue by karthiksubramanians** [steveloughran/winutils#16]
Will Winutils for Hadoop 3.0.0 work for 3.1.1?

**Comment by steveloughran** [comment]
I think it should, but really I need to cut a new release. It looks like I've got a whole batch of releases to catch up on

**Comment by John3-16** [comment]
Just finished building 3.1.1 on Windows 10 with VS2017 what a trip that was.

**Comment by steveloughran** [comment]
wow. I feel your pain

**Comment by steveloughran** [comment]
any specific issues (like things which need to go back into hadoop itself)

**Comment by steveloughran** [comment]
(FWIW, you now know why nobody, not even microsoft, ships hadoop on windows)

**Comment by thomasjungblut** [comment]
@John3-16 good job! Care to share?

> (FWIW, you now know why nobody, not even microsoft, ships hadoop on windows)

we tried and failed  ¯\_(ツ)_/¯

**Comment by steveloughran** [comment]
FWIW, given that the main use of file:// on windows is people trying to use spark standalone on their laptops, we should be able to make it possible do to this *without worrying about the fact that there isn't a native lib there*. Really, it's not solving problems which people playing in spark shell need solved. If we could allow people to just tell hadoop that it didn't need to worry about its absence, then everyone would be happy

**Comment by thomasjungblut** [comment]
Which version of Java does Hadoop compile with nowadays? 
I reckon the Java 7 (?) `Files` operations are good and stable and can be used instead of the native libs. My pain point is almost always the `chmod`, which can also be set via `Files#setPosixFilePermissions`.

**Comment by steveloughran** [comment]
> I reckon the Java 7 (?) `Files` operations are good and stable and can be used instead of the native libs.

+1

**Comment by steveloughran** [comment]
FWIW the need for that native lib is a PITA even in hadoop's own test code. As the YARN RM/NM won't come up with Kerberos turned on and without that native lib, so I can't run Kerberized mini-YARN clusters (I tried in HADOOP-14556 and after a week gave up)
