### ISSUE TITLE
Runtime Dependencies 

### ISSUE THREAD

**Issue by gillotte** [steveloughran/winutils#2]
Hi, 

It would be very helpful to know which version of the VC++ Runtime these are compiled against and the version of the Windows SDK used. 

I'm trying to run spark on a clean box and I'm running into native io, errors in hadoop dll.

Thanks for compiling this!

**Comment by steveloughran** [comment]
Good question
```
C:\Work\hadoop-trunk>cl
Microsoft (R) C/C++ Optimizing Compiler Version 16.00.30319.01 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.
```
Visual Studio 10, 2010. running on a Windows Server 2012 machine. Everything is building and I don't want to touch the VM for a while; it's only ever booted up for building and testing releases

**Comment by steveloughran** [comment]
@gillotte : updated the [project README](https://github.com/steveloughran/winutils/blob/master/README.md) with all the details for the 2.8.0 RC3 build and test run.

Hadoop 2.8 is meant to improve reporting on failures if WINUTILS.EXE is missing, see [HADOOP-10775](https://issues.apache.org/jira/browse/HADOOP-10775). Please grab the 2.8.0 build and test this.

I'm going to close this as done with the doc improvements
