### ISSUE TITLE
when mapreduce submit a task to yarn have an error

### ISSUE THREAD

**Issue by exploreing** [steveloughran/winutils#20]
I submit this task from windows to linux have an error,
Error: cannot find or load main class    org.apache.hadoop.mapreduce.v2.app.MRAppMaster,How should I solve this problem，Please reply to me soon，Thank!

**Comment by cdarlint** [comment]
I believe this means it can not find jars of hadoop
However this issue depends on your configuration and there may not be a turn-key solution
simple search on google returns a lot result
and they describe the problem in more details, and their solutions are still not simple (i.e. need to check a lot configurations)
