### ISSUE TITLE
Support for Hadoop 3.2

### ISSUE THREAD

**Issue by Glamdring** [steveloughran/winutils#21]
I'm using Hadoop 3.2 and it fails with missing native methods (if I use the 3.0.0 dll).

**Comment by mystic-cg** [comment]
FYI.
https://github.com/cdarlint/winutils

**Comment by steveloughran** [comment]
WONTFIX, sorry. I'm not set up to build windows binaries any more

I'd prefer someone removed the need for it entirely [HADOOP-13223. winutils.exe is a bug nexus and should be killed with an axe.](https://issues.apache.org/jira/browse/HADOOP-13223).

Pull requests welcome there.
