### ISSUE TITLE
Problem while executing spark shell

### ISSUE THREAD

**Issue by sachinagnihotri** [steveloughran/winutils#6]
I have done all step by step..but after step 6 ..executing spark-shell is doing nothing but taking to the same command line
for example:
D:\>spark\spark2.2.0-bin-hadoop2.7\bin\spark-shell
after executing this I get the following: no error but nothing happened.

D:\>spark\spark2.2.0-bin-hadoop2.7\bin\

**Comment by steveloughran** [comment]
sorry, you're going to be left debugging this yourself. try logging `org.apache.hadoop.util.Shell` at debug to see if it says more.
