### ISSUE TITLE
Windows 10: winutils.exe doesn't work

### ISSUE THREAD

**Issue by sergey-derugo** [steveloughran/winutils#7]
It's not possible run the Winutils.exe due to the error:

`
winutils.exe - System Error
The code execution cannot proceed because MSVCR100.dll was not found. Reinstalling the program may fix this problem. 
`

Or stack-trace from from Hadoop:
`
Caused by: ExitCodeException exitCode=-1073741515: 
	at org.apache.hadoop.util.Shell.runCommand(Shell.java:575)
	at org.apache.hadoop.util.Shell.run(Shell.java:478)
	at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:766)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:859)
	at org.apache.hadoop.util.Shell.execCommand(Shell.java:842)
`

P.S. There is workaround - install the VC++ redistributable packages. See details here https://answers.microsoft.com/en-us/insider/forum/insider_wintp-insider_repair/how-do-i-fix-this-error-msvcp100dll-is-missing/c167d686-044e-44ab-8e8f-968fac9525c5?auth=1

**Comment by kokorin** [comment]
@sergey-derugo Thank you! I spent several hours solving the issue

**Comment by steveloughran** [comment]
WONTFIX, sorry. I'm not set up to build windows binaries any more

I'd prefer someone removed the need for it entirely [HADOOP-13223. winutils.exe is a bug nexus and should be killed with an axe.](https://issues.apache.org/jira/browse/HADOOP-13223).

Pull requests welcome there.

**Comment by amanjyotiparida840** [comment]
I don't know which system you have used, If it's the case of windows, especially 64 bit, then you must have tried this out may be it would work for you.
Just copy MSVCR100.dll file from C:\Windows\SysWOW64
And paste it near your winutils.exe file, reboot your machine and again try to execute that........
Hope this work for you.....

**Comment by kaneriaanand** [comment]
> I don't know which system you have used, If it's the case of windows, especially 64 bit, then you must have tried this out may be it would work for you. Just copy MSVCR100.dll file from C:\Windows\SysWOW64 And paste it near your winutils.exe file, reboot your machine and again try to execute that........ Hope this work for you.....

I copied MSVCR100.dll file from C:\Windows\SysWOW64 and restarted. Now the exit code is changed from -1073741515 to 1073741701

**Comment by steveloughran** [comment]
wontfix i'm afraid. at least not from my repo. someone at MSFT is still working on hadoop on windows though...

**Comment by steveloughran** [comment]
-1073741515 is C0000135 in twos complement hex, error code "DLL not found"

https://stackoverflow.com/questions/11432940/what-does-error-code-0xc0000135-mean-when-starting-a-net-application#:~:text=This%20error%20is%20caused%20when,framework%20before%20running%20the%20application.
