### ISSUE TITLE
Command "winutils systeminfo" returns an error on Windows 7  64 bit

### ISSUE THREAD

**Issue by Nail-S** [steveloughran/winutils#9]
The command "winutils systeminfo" returns an error with the code 1 and a message PdhAddCounter \Network Interface(*)\Bytes Received/Sec failed with 0xc0000bb8. Error in GetDiskAndNetwork. Err:1 when running Hadoop 3.0.0 on Windows 7 64 bit

**Comment by steveloughran** [comment]
ok. File an issue on [apache JIRA](https://issues.apache.org/jira/secure/Dashboard.jspa) under HADOOP

**Comment by gianlucastrada** [comment]
I've same problem for hadoop: 
ExitCodeException exitCode=1: PdhAddCounter \Network Interface(*)\Bytes Received/Sec failed with 0xc0000bb8 Please, help me!

**Comment by steveloughran** [comment]
I'd search for "windows error  0xc0000bb8" and see what you find
